/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.leadws.tela;

import br.com.leadws.Controller.GerarLeadController;
import br.com.leadws.facade.ParametrosLeadFacade;
import br.com.leadws.model.Parametroslead;
import java.awt.Toolkit;
import java.util.Timer;
import java.util.TimerTask;


/**
 *
 * @author jizid
 */
public final class FrmLead extends javax.swing.JFrame {

    
    public Toolkit toolkit;
    public Timer timer;
    private Parametroslead parametrosLead;
    /**
     * Creates new form FrmLead
     */
    public FrmLead() {
        initComponents();
        ParametrosLeadFacade parametrosLeadFacade = new ParametrosLeadFacade();
        parametrosLead = parametrosLeadFacade.get();
        primeiraLeitura();
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Carregamento de Leads");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLead().setVisible(true);
            }
        });
    }
    
    public void primeiraLeitura(){
        GerarLeadController gerarLeadController = new GerarLeadController(parametrosLead);
        gerarLeadController.gerarListaUnidade();
        if (gerarLeadController.getIdContato() > 0) {
            ParametrosLeadFacade parametrosLeadFacade = new ParametrosLeadFacade();
            parametrosLead.setIdcontato(gerarLeadController.getIdContato());
            parametrosLead = parametrosLeadFacade.salvar(parametrosLead);
        }
    }
    
    
    public void  iniciar() {
        toolkit = Toolkit.getDefaultToolkit();
        timer = new Timer();
        TimerTask timerTask = new TimerTask(){
            @Override
            public void run() {
                GerarLeadController gerarLeadController = new GerarLeadController(parametrosLead);
                gerarLeadController.gerarListaUnidade();
                if (gerarLeadController.getIdContato() > 0) {
                    ParametrosLeadFacade parametrosLeadFacade = new ParametrosLeadFacade();
                    parametrosLead.setIdcontato(gerarLeadController.getIdContato());
                    parametrosLead = parametrosLeadFacade.salvar(parametrosLead);
                }
            }
        };
        timer.scheduleAtFixedRate(timerTask, (parametrosLead.getTemporizador() * 60 *1000), (parametrosLead.getTemporizador() * 60 *1000));
    }   

   
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
