/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.leadws.tela;

import br.com.leadws.Controller.GerarLeadController;
import br.com.leadws.facade.ContatoFacade;
import br.com.leadws.facade.ParametrosLeadFacade;
import br.com.leadws.facade.UnidadeFacade;
import br.com.leadws.facade.UsuarioFacade;
import br.com.leadws.model.Importlead;
import br.com.leadws.model.Leads;
import br.com.leadws.model.Parametroslead;
import br.com.leadws.model.Unidadenegocio;
import br.com.leadws.model.Usuario;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;


/**
 *
 * @author jizid
 */
public final class FrmLead extends javax.swing.JFrame {

    
    public Toolkit toolkit;
    public Timer timer;
    private Parametroslead parametrosLead;
    /**
     * Creates new form FrmLead
     */
    public FrmLead() {
        initComponents();
        ParametrosLeadFacade parametrosLeadFacade = new ParametrosLeadFacade();
        parametrosLead = parametrosLeadFacade.get();
        primeiraLeitura();
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextunidade = new javax.swing.JTextField();
        jTextpublicidade = new javax.swing.JTextField();
        jTextdescunidade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Carregamento de Leads");

        jButton1.setText("Inportar Excel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton1)))
                .addGap(77, 77, 77))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jTextunidade, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextdescunidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextpublicidade)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextunidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextpublicidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextdescunidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       List<Importlead> lista = new ArrayList<Importlead>();
       GerarLeadController gerarLeadController = new GerarLeadController(parametrosLead);
        Unidadenegocio unidade = new Unidadenegocio();;
        UnidadeFacade unidadeFacade = new UnidadeFacade();
        unidade = unidadeFacade.getUsuarioResponsavel(Integer.parseInt(jTextunidade.getText()));
        Usuario usuario = new Usuario();
        UsuarioFacade usuarioFacade  = new UsuarioFacade();
        usuario = usuarioFacade.consultar(unidade.getIdunidadeNegocio()).get(0);
       if (lista!=null){
           for(int i=0;i<lista.size();i++){
               Importlead importe = lista.get(i);
               Leads lead = new Leads();
               lead.setEmail(importe.getEmail());
               lead.setMensagem(importe.getNota() + " " + importe.getObservacao());
               lead.setNome(importe.getNome() + " " + importe.getSobrenome());
               lead.setTelefone(importe.getFone());
               lead.setDatanascimento(importe.getDatanascimento());
               lead.setUnidade(Integer.parseInt(jTextdescunidade.getText()));
               lead.setUnidade_desc(jTextdescunidade.getText());
               lead.setUrlclient("Feira");
               lead.setPublicidade(Integer.parseInt(jTextpublicidade.getText()));
               gerarLeadController.salvarLeads(lead, usuario, unidade, false);
           }
           
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLead().setVisible(true);
            }
        });
    }
    
    public void primeiraLeitura(){
        GerarLeadController gerarLeadController = new GerarLeadController(parametrosLead);
        gerarLeadController.gerarListaUnidade();
        ContatoFacade contatoFacade = new ContatoFacade();
        int idContato = contatoFacade.getIdLead();
        if (idContato > 0) {
            ParametrosLeadFacade parametrosLeadFacade = new ParametrosLeadFacade();
            parametrosLead.setIdcontato(idContato);
            parametrosLead = parametrosLeadFacade.salvar(parametrosLead);
        }
    }
    
    
    public void  iniciar() {
        toolkit = Toolkit.getDefaultToolkit();
        timer = new Timer();
        TimerTask timerTask = new TimerTask(){
            @Override
            public void run() {
                GerarLeadController gerarLeadController = new GerarLeadController(parametrosLead);
                gerarLeadController.gerarListaUnidade();
                ContatoFacade contatoFacade = new ContatoFacade();
                int idContato = contatoFacade.getIdLead();
                if (idContato > 0) {
                    ParametrosLeadFacade parametrosLeadFacade = new ParametrosLeadFacade();
                    parametrosLead.setIdcontato(idContato);
                    parametrosLead = parametrosLeadFacade.salvar(parametrosLead);
                }
            }
        };
        timer.scheduleAtFixedRate(timerTask, (parametrosLead.getTemporizador() * 60 *1000), (parametrosLead.getTemporizador() * 60 *1000));
    }   

   
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextdescunidade;
    private javax.swing.JTextField jTextpublicidade;
    private javax.swing.JTextField jTextunidade;
    // End of variables declaration//GEN-END:variables
}
